### ISSUE TITLE
mapfish_print.py 

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb#1474]
mapfish_print.py stops with error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.7/site-packages/waitress/channel.py", line 397, in service
    task.service()
  File "/app/.venv/lib/python3.7/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/app/.venv/lib/python3.7/site-packages/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/router.py", line 245, in invoke_request
    response = handle_request(request)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/app/.venv/lib/python3.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/router.py", line 144, in handle_request
    registry, request, context, context_iface, view_name
  File "/app/.venv/lib/python3.7/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/viewderivers.py", line 392, in viewresult_to_response
    result = view(context, request)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/viewderivers.py", line 113, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/app/.venv/lib/python3.7/site-packages/pyramid_oereb/core/views/webservice.py", line 309, in get_extract_by_id
    request=self._request
  File "/app/.venv/lib/python3.7/site-packages/pyramid/renderers.py", line 130, in render_to_response
    result = helper.render_to_response(value, None, request=request)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/renderers.py", line 466, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/app/.venv/lib/python3.7/site-packages/pyramid/renderers.py", line 462, in render
    result = renderer(value, system_values)
  File "/app/.venv/lib/python3.7/site-packages/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py", line 86, in __call__
    self.convert_to_printable_extract(extract_as_dict, feature_geometry)
  File "/app/.venv/lib/python3.7/site-packages/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py", line 476, in convert_to_printable_extract
    self.sort_restriction_on_landownership_documents(restriction_on_landownership)
  File "/app/.venv/lib/python3.7/site-packages/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py", line 655, in sort_restriction_on_landownership_documents
    Renderer.sort_legal_provision
  File "/app/.venv/lib/python3.7/site-packages/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py", line 672, in sort_dict_list
    return sorted(legend_list, key=sort_keys)
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
Can provide the resulting json if useful.

**Comment by jwkaltz** [comment]
So in your case, one of the legal provisions is "None", it's strange that the code gets this far without an error. I guess this should be checked further up to get a clearer error message. 
Did you check the data extract itself (XML or JSON), do the legal provisions look OK?

**Comment by vvmruder** [comment]
@michmuel Yes provide what you have please :)

**Comment by michmuel** [comment]
Attached the json produced by pyramid_oereb for E-Grid CH882707397041. The Oereb Client handles well the query.

[CH882707397041.json.zip](https://github.com/openoereb/pyramid_oereb/files/7911894/CH882707397041.json.zip)

**Comment by michmuel** [comment]
I does not have had a close look to this function so far. Maybe someone knows the code better and might fix it faster.
One issue might be that the official number is not mandatory and does not have to be provided for each legal provision. That could be a problem for sorting.
