### ISSUE TITLE
create_standard_tables only works with sql_file

### ISSUE THREAD

**Issue by CoNussberger** [openoereb/pyramid_oereb#1563]
The create_standard_tabels skript does only work if  the tabel definitions are written to a sql file.
Expected behaviour: if no sql_file is given tables are created in the database defined in pyramid_oereb.yml.mako.

**Comment by jwkaltz** [comment]
@CoNussberger I think this issue as well might be solved in the open PR https://github.com/openoereb/pyramid_oereb/pull/1547
Could you test that PR?

**Comment by CoNussberger** [comment]
I still get the following error

```
Traceback (most recent call last):
  File "/venvs/.venv/bin/create_standard_tables", line 11, in <module>
    load_entry_point('pyramid-oereb', 'console_scripts', 'create_standard_tables')()
  File "/workspace/pyramid_oereb/contrib/data_sources/standard/create_tables.py", line 71, in create_standard_tables
    tables_only=options.tables_only
  File "/workspace/pyramid_oereb/contrib/data_sources/create_tables.py", line 74, in create_tables_from_standard_configuration
    if_not_exists=if_not_exists
  File "/workspace/pyramid_oereb/contrib/data_sources/create_tables.py", line 38, in create_theme_tables_
    sql_file.write(sql)
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by vvmruder** [comment]
@vvmruder recheck

**Comment by voisardf** [comment]
@jwkaltz can be deleted and closed if not used anymore
