### ISSUE TITLE
Import script for Federal topics stucks while parsing 'motorways_building_lines'

### ISSUE THREAD

**Issue by thomasmarti** [openoereb/pyramid_oereb#816]
Since 19.03.2019 the Import script for Federal topics stucks while parsing 'motorways_building_lines'. I suppose astra has made a data update a day before.

The script hangs at the following step:
`2019-03-19 16:12:22,134 [INFO] import_federal_topic: Parsing ./f32f0a5c-8cc0-4bda-8de5-45adf6b4e2b2/ch.astra.baulinien-nationalstrassen.oereb_20190318.xtf`

Full output:
```
2019-03-19 16:12:19,454 [INFO] import_federal_topic: Downloading data from https://data.geo.admin.ch/ch.astra.projektierungszonen-nationalstrassen.oereb/data.zip
2019-03-19 16:12:20,580 [INFO] import_federal_topic: Saving file to ./59014917-994b-46cd-a6ea-3d79ed573790.zip
470KB [00:00, 7.39kKB/s]
2019-03-19 16:12:20,647 [INFO] import_federal_topic: Extracting ./59014917-994b-46cd-a6ea-3d79ed573790.zip to ./59014917-994b-46cd-a6ea-3d79ed573790
2019-03-19 16:12:20,647 [INFO] import_federal_topic:    ch.astra.projektierungszonen-nationalstrassen.oereb_20171130.xtf
2019-03-19 16:12:20,648 [INFO] import_federal_topic:    ch.astra.projektierungszonen-nationalstrassen.oereb_20171130.md5.txt
2019-03-19 16:12:20,648 [INFO] import_federal_topic:    OeREBKRM_V1_1_Gesetze_20180501.xml
2019-03-19 16:12:20,648 [INFO] import_federal_topic: Deleting ./59014917-994b-46cd-a6ea-3d79ed573790.zip
2019-03-19 16:12:20,649 [INFO] import_federal_topic: Current checksum: 4ba7ed42a81f3ef6eb0f0a90cd627e39
2019-03-19 16:12:20,649 [INFO] import_federal_topic: Found law source file: ./59014917-994b-46cd-a6ea-3d79ed573790/OeREBKRM_V1_1_Gesetze_20180501.xml
2019-03-19 16:12:20,649 [INFO] import_federal_topic: Found topic source file: ./59014917-994b-46cd-a6ea-3d79ed573790/ch.astra.projektierungszonen-nationalstrassen.oereb_20171130.xtf
2019-03-19 16:12:20,651 [INFO] import_federal_topic: Starting import of topic MotorwaysProjectPlaningZones
2019-03-19 16:12:20,651 [INFO] import_federal_topic: Using SRID: 2056
2019-03-19 16:12:20,651 [INFO] import_federal_topic: Maximum difference for arc points: 0.001
2019-03-19 16:12:20,651 [INFO] import_federal_topic: Arc point coordinate precision: 3
2019-03-19 16:12:20,652 [INFO] import_federal_topic: Truncating tables:
2019-03-19 16:12:20,652 [INFO] import_federal_topic:     motorways_project_planing_zones.office
2019-03-19 16:12:20,715 [INFO] import_federal_topic:     motorways_project_planing_zones.data_integration
2019-03-19 16:12:20,719 [INFO] import_federal_topic:     motorways_project_planing_zones.reference_definition
2019-03-19 16:12:20,726 [INFO] import_federal_topic:     motorways_project_planing_zones.document_base
2019-03-19 16:12:20,745 [INFO] import_federal_topic:     motorways_project_planing_zones.document
2019-03-19 16:12:20,758 [INFO] import_federal_topic:     motorways_project_planing_zones.article
2019-03-19 16:12:20,761 [INFO] import_federal_topic:     motorways_project_planing_zones.view_service
2019-03-19 16:12:20,789 [INFO] import_federal_topic:     motorways_project_planing_zones.legend_entry
2019-03-19 16:12:20,795 [INFO] import_federal_topic:     motorways_project_planing_zones.public_law_restriction
2019-03-19 16:12:20,820 [INFO] import_federal_topic:     motorways_project_planing_zones.geometry
2019-03-19 16:12:20,824 [INFO] import_federal_topic:     motorways_project_planing_zones.public_law_restriction_base
2019-03-19 16:12:20,828 [INFO] import_federal_topic:     motorways_project_planing_zones.public_law_restriction_refinement
2019-03-19 16:12:20,832 [INFO] import_federal_topic:     motorways_project_planing_zones.public_law_restriction_document
2019-03-19 16:12:20,836 [INFO] import_federal_topic:     motorways_project_planing_zones.document_reference
2019-03-19 16:12:20,840 [INFO] import_federal_topic:     motorways_project_planing_zones.document_reference_definition
2019-03-19 16:12:20,843 [INFO] import_federal_topic: Parsing ./59014917-994b-46cd-a6ea-3d79ed573790/OeREBKRM_V1_1_Gesetze_20180501.xml
2019-03-19 16:12:20,884 [INFO] import_federal_topic: Parsing ./59014917-994b-46cd-a6ea-3d79ed573790/ch.astra.projektierungszonen-nationalstrassen.oereb_20171130.xtf
2019-03-19 16:12:20,885 [INFO] import_federal_topic: Committing import
2019-03-19 16:12:20,910 [INFO] import_federal_topic: Finished import of topic MotorwaysProjectPlaningZones
2019-03-19 16:12:20,911 [INFO] import_federal_topic: Deleting folder ./59014917-994b-46cd-a6ea-3d79ed573790
/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2019-03-19 16:12:21,588 [INFO] import_federal_topic: Downloading data from https://data.geo.admin.ch/ch.astra.baulinien-nationalstrassen.oereb/data.zip
2019-03-19 16:12:21,817 [INFO] import_federal_topic: Saving file to ./f32f0a5c-8cc0-4bda-8de5-45adf6b4e2b2.zip
1.47kKB [00:00, 23.2kKB/s]
2019-03-19 16:12:21,881 [INFO] import_federal_topic: Extracting ./f32f0a5c-8cc0-4bda-8de5-45adf6b4e2b2.zip to ./f32f0a5c-8cc0-4bda-8de5-45adf6b4e2b2
2019-03-19 16:12:21,882 [INFO] import_federal_topic:    ch.astra.baulinien-nationalstrassen.oereb_20190318.md5.txt
2019-03-19 16:12:21,882 [INFO] import_federal_topic:    ch.astra.baulinien-nationalstrassen.oereb_20190318.xtf
2019-03-19 16:12:21,904 [INFO] import_federal_topic:    OeREBKRM_V1_1_Gesetze_20180501.xml
2019-03-19 16:12:21,905 [INFO] import_federal_topic: Deleting ./f32f0a5c-8cc0-4bda-8de5-45adf6b4e2b2.zip
2019-03-19 16:12:21,905 [INFO] import_federal_topic: Current checksum: 245847d210b3a997a2f4ea42b89fcf2f
2019-03-19 16:12:21,906 [INFO] import_federal_topic: Found law source file: ./f32f0a5c-8cc0-4bda-8de5-45adf6b4e2b2/OeREBKRM_V1_1_Gesetze_20180501.xml
2019-03-19 16:12:21,906 [INFO] import_federal_topic: Found topic source file: ./f32f0a5c-8cc0-4bda-8de5-45adf6b4e2b2/ch.astra.baulinien-nationalstrassen.oereb_20190318.xtf
2019-03-19 16:12:21,908 [INFO] import_federal_topic: Starting import of topic MotorwaysBuildingLines
2019-03-19 16:12:21,908 [INFO] import_federal_topic: Using SRID: 2056
2019-03-19 16:12:21,908 [INFO] import_federal_topic: Maximum difference for arc points: 0.001
2019-03-19 16:12:21,908 [INFO] import_federal_topic: Arc point coordinate precision: 3
2019-03-19 16:12:21,908 [INFO] import_federal_topic: Truncating tables:
2019-03-19 16:12:21,908 [INFO] import_federal_topic:     motorways_building_lines.office
2019-03-19 16:12:21,967 [INFO] import_federal_topic:     motorways_building_lines.data_integration
2019-03-19 16:12:21,971 [INFO] import_federal_topic:     motorways_building_lines.reference_definition
2019-03-19 16:12:21,978 [INFO] import_federal_topic:     motorways_building_lines.document_base
2019-03-19 16:12:22,003 [INFO] import_federal_topic:     motorways_building_lines.document
2019-03-19 16:12:22,020 [INFO] import_federal_topic:     motorways_building_lines.article
2019-03-19 16:12:22,023 [INFO] import_federal_topic:     motorways_building_lines.view_service
2019-03-19 16:12:22,046 [INFO] import_federal_topic:     motorways_building_lines.legend_entry
2019-03-19 16:12:22,050 [INFO] import_federal_topic:     motorways_building_lines.public_law_restriction
2019-03-19 16:12:22,075 [INFO] import_federal_topic:     motorways_building_lines.geometry
2019-03-19 16:12:22,079 [INFO] import_federal_topic:     motorways_building_lines.public_law_restriction_base
2019-03-19 16:12:22,082 [INFO] import_federal_topic:     motorways_building_lines.public_law_restriction_refinement
2019-03-19 16:12:22,086 [INFO] import_federal_topic:     motorways_building_lines.public_law_restriction_document
2019-03-19 16:12:22,089 [INFO] import_federal_topic:     motorways_building_lines.document_reference
2019-03-19 16:12:22,093 [INFO] import_federal_topic:     motorways_building_lines.document_reference_definition
2019-03-19 16:12:22,097 [INFO] import_federal_topic: Parsing ./f32f0a5c-8cc0-4bda-8de5-45adf6b4e2b2/OeREBKRM_V1_1_Gesetze_20180501.xml
2019-03-19 16:12:22,134 [INFO] import_federal_topic: Parsing ./f32f0a5c-8cc0-4bda-8de5-45adf6b4e2b2/ch.astra.baulinien-nationalstrassen.oereb_20190318.xtf
2019-03-19 16:12:22,134 [INFO] import_federal_topic: Parsing ./f32f0a5c-8cc0-4bda-8de5-45adf6b4e2b2/ch.astra.baulinien-nationalstrassen.oereb_20190318.xtf

```

**Comment by thomasmarti** [comment]
The Import is not stucking, it a lot more slower than before (28 minutes) as the amount of date has probably been increased.

Is this behavior considered as normal?

**Comment by jwkaltz** [comment]
@thomasmarti We can not reproduce the import being long, when we execute it, it lasts 4 seconds. Maybe it was a temporary problem in your network or on the federal server side? Can you please try again?

**Comment by thomasmarti** [comment]
@jwkaltz I have still the problem on the dev- and -integrationsystems. Seems as the scripts hangs 30 Minutes until a timeout is reached. On the productionsystem the script is behaving as expected.

You can close the issue. I have to narrow the problem down in our environment. Any hints are welcome

**Comment by thomasmarti** [comment]
@jwkaltz Note: when interrupting the script with ctl,c the following errorMessage ist displayed:

> 2019-03-28 14:46:42,723 [INFO] import_federal_topic: Parsing ./55fdd657-51aa-422a-8aa9-e01bb2a037bc/ch.astra.baulinien-nationalstrassen.oereb_20190327.xtf
> ^CTraceback (most recent call last):
>   File "/usr/local/bin/import_federal_topic", line 10, in <module>
>     sys.exit(run())
>   File "/usr/local/lib/python2.7/site-packages/pyramid_oereb/standard/import_federal_topic.py", line 128, in run
>     loader.load(files, force=options.force)
>   File "/usr/local/lib/python2.7/site-packages/pyramid_oereb/standard/xtf_import/__init__.py", line 125, in load
>     self._parse_datasection(session, element)
>   File "/usr/local/lib/python2.7/site-packages/pyramid_oereb/standard/xtf_import/__init__.py", line 232, in _parse_datasection
>     self._parse_transfer_structure(session, element, laws=laws)
>   File "/usr/local/lib/python2.7/site-packages/pyramid_oereb/standard/xtf_import/__init__.py", line 299, in _parse_transfer_structure
>     geometry.parse(element)
>   File "/usr/local/lib/python2.7/site-packages/pyramid_oereb/standard/xtf_import/geometry.py", line 46, in parse
>     geom=self._parse_geom(geometry)
>   File "/usr/local/lib/python2.7/site-packages/pyramid_oereb/standard/xtf_import/geometry.py", line 60, in _parse_geom
>     geom = self._parse_line(element, 21781)
>   File "/usr/local/lib/python2.7/site-packages/pyramid_oereb/standard/xtf_import/geometry.py", line 104, in _parse_line
>     coords.extend(self._parse_arc(coord, coords[-1], srs))
>   File "/usr/local/lib/python2.7/site-packages/pyramid_oereb/standard/xtf_import/geometry.py", line 141, in _parse_arc
>     arc_point = self._reprojector.transform((a['x'], a['y']), from_srs=srs, to_srs=self._to_srs)
>   File "/usr/local/lib/python2.7/site-packages/pyreproj/__init__.py", line 87, in transform
>     from_proj = self.__get_proj_from_parameter__(from_srs)
>   File "/usr/local/lib/python2.7/site-packages/pyreproj/__init__.py", line 118, in __get_proj_from_parameter__
>     proj = Proj(init='epsg:{0}'.format(param))
>   File "/usr/local/lib/python2.7/site-packages/pyproj/__init__.py", line 322, in __init__
>     self.crs = CRS.from_user_input(projparams if projparams is not None else kwargs)
>   File "/usr/local/lib/python2.7/site-packages/pyproj/crs.py", line 218, in from_user_input
>     return cls(**value)
>   File "/usr/local/lib/python2.7/site-packages/pyproj/crs.py", line 140, in __init__
>     super(CRS, self).__init__(projstring)
>   File "pyproj/_crs.pyx", line 319, in pyproj._crs._CRS.__init__
>   File "/usr/local/lib/python2.7/site-packages/pyproj/compat.py", line 23, in pystrdecode
>     def pystrdecode(cstr):
> KeyboardInterrupt

**Comment by thomasmarti** [comment]
@jwkaltz 
calling the import without coordinate transformation, works:

`import_federal_topic -c config/config.yml -t MotorwaysBuildingLines -f -S 21781`

**Comment by kdeininger** [comment]
@thomasmarti, do you still encounter problems with the import script or could you solve it?

**Comment by jwkaltz** [comment]
@thomasmarti As this seems to have been an intermittent issue related to your network environment, I am closing this issue.
